### ISSUE TITLE
SideChain breaks in server-side rendering situations

### ISSUE THREAD

**Issue by lajoiemedia** [nprapps/sidechain#7]
I'm using a dynamic-height iframe in a project made with sveltekit.

SideChain breaks when imported on the server-side because it subclasses HTMLElement, which isn't defined outside the browser. Pym.js works fine for this use case, which is why I suspect Reuters is still using it in their own sveltekit-based graphics rig. (See: https://github.com/reuters-graphics/graphics-components/blob/main/src/components/PymChild/PymChild.svelte)

It would be great if sidechain could be stubbed out on the server side, so that if it's imported in a node environment it just does nothing or exports an empty object, rather than crashing because HTMLElement is undefined.

**Comment by thomaswilburn** [comment]
There's not really a way around this on the Sidechain side, since this is just how custom elements function--they have to extend HTMLElement to work. For server-side rendering, you could provide a polyfill for the element on the global scope that it could subclass, and which would stub out the DOM methods and properties that Sidechain uses, either with SSR equivalents or null amounts.

You probably wouldn't have to do much besides an empty HTMLElement class and a stub for window.customElements, since all the actual work that `<side-chain>` does is in lifecycle callbacks that just wouldn't be called. But I don't have any direct SSR experience to say for sure.

The Reuters example you link to does not, as far as I can tell, run in SSR. If it did, it would break as well, since Pym creates and manipulates DOM APIs during child instance creation that don't exist in Node.

**Comment by thomaswilburn** [comment]
(Alternately, it may be worth investigating whether it's possible to interact with the Sveltekit adapter or the underlying Vite/Rollup layer to provide the equivalent of an import map, which could import an empty module on the server and the actual Sidechain code in the bundler.

Alternately alternately, you might try using async imports so that you could conditionally load Sidechain only when Svelte indicates through its environment variables that it's running in a browser.)

**Comment by lajoiemedia** [comment]
Couldn't you do something like this in the library?
```js
let SideChain = undefined;
if (typeof HTMLElement !== "undefined") {
  SideChain = class extends HTMLElement {
    ...
  }
}
export default SideChain;
```

**Comment by thomaswilburn** [comment]
I guess in theory we could, but it's a custom element. It's not unreasonable for Sidechain to assume it runs in an environment that provides the globals it relies on as a prerequisite for its use. I don't think it should be on the burden of the library to accommodate runtime environments where it literally can't run unassisted.

**Comment by lajoiemedia** [comment]
No one expects it to run in a node/server environment, but with widespread adoption of SSR and SSG, it's increasingly an expectation that libraries at least don't crash on import in a node environment. I don't think it's an unreasonable expectation that a library fail gracefully.

News sites these days run on things like nextJS, sveltekit, ArcXP, etc. They all use the same sort of isomorphic setup. You'd be making sidechain much easier to adopt in these circumstances with a fairly minor tweak to the code.

**Comment by thomaswilburn** [comment]
Pagliacci goes to the doctor, says "Doctor, it hurts when I twist my elbow the wrong way."

Doctor says, "So **stop twisting it that way**. Also, have you heard of this Pagliacci guy? Incredible show, go see it, it'll take your mind right off the whole elbow thing."

This is all a little bit of a moot point for your purposes--I have commit rights to this repo because it was my baby while I was at NPR and Aly was very kind to offer to let me support it, but I don't have permissions anymore to deploy Sidechain to NPM, since I'm no longer a part of the organization. If it matters to you that this is addressed promptly, you may want to fork and install into your project via a Git URL in your package.json.

Regardless, if there *were* a serious discussion about this change among people with deployment access, I would argue that from my perspective it makes more sense for SSR projects to conditionally import Sidechain than it does for the library to try to figure out under which circumstances we should be a no-op. All modern SSR frameworks have mechanisms for doing so--Next has `dynamic()`, Svelte has async imports in `onMount`, Vue has the `mounted` lifecycle hook--and these are all explicitly blessed solutions for this scenario.

It's a similar situation to the web component polyfills, which used to ship with Sidechain and are no longer included by default, because people who are in a situation where they want to use it in an incompatible runtime are in the best place to understand what they need to add in order to fill out that support matrix.

**Comment by lajoiemedia** [comment]
It isn't urgent for this to be addressed, since I've already pulled out the code that used SideChain and replaced it with Pym. I suspect Reuters made the same decision after realizing how un-ergonomic SideChain is to use in an SSR/SSG environment. (Yes, there are possible dynamic load solutions, but they are complex and fragile in combination with bundling.) Ultimately, it's your (and NPR's) library and you can do what you want, but you're very much swimming against the current of the industry here. Ultimately, the impact will be lack of adoption, as people stick with Pym or roll their own solutions.

You've already semi-embraced the node ecosystem -- this is an NPM package, after all. It doesn't seem so far-fetched that the whole thing shouldn't explode on import in a node script.

Oh, there is another possible solution, in case you prefer it. The package.json can be written to have a different entry point for node.

```js
// package.json
{
  "exports": {
    "default": "./index.js",
    "node": "./index-node.js"
  },
  "type": "module"
} 
```

Anyway, thanks for responding so promptly and thoroughly (even if we disagree). I've made my case and I believe it's supported by what most other major utility libraries are doing. Finally, I'll just mention: you do realize that the doctor in the Pagliacci story isn't a good doctor, right? :-)
